In [2]:
import numpy as np

In [8]:
a = np.array([10, 20, 30])
b = np.array([5, 15, 25])
print(a)
print(b)
print(a-b)

[10 20 30]
[ 5 15 25]
[5 5 5]


In [11]:
lst = [3,4,5]
newArr = np.array(lst)
print(lst)
print(newArr)
print(type(newArr))

[3, 4, 5]
[3 4 5]
<class 'numpy.ndarray'>


In [16]:
arr = np.array([[10,20,30,40], [50,60,70,80], [5,15,25,35]])
print(arr)
print(type(arr))

[[10 20 30 40]
 [50 60 70 80]
 [ 5 15 25 35]]
<class 'numpy.ndarray'>


In [24]:
# slicing of array arr[0:3]
# means from 0th index to (3-1)nd index
arr = np.array([10,20,30,40])
print(arr[0:3])

[10 20 30]


In [56]:
arr = np.array([[10,20,30,40], [50,60,70,80], [5,15,25,35]])
print(arr[0:2,0:3]) # 0and1 row, 0,1,2 column in each row --> matrix
print(arr[0:1,1:3]) # matrix
print(arr[0,1:3]) # array

[[10 20 30]
 [50 60 70]]
[[20 30]]
[20 30]


In [49]:
# attributes of np array
print(np.shape(arr)) # dimension of matrix array
print(np.size(arr)) # total no. of elements in matrix array
print(np.ndim(arr)) # no. of dimension of array
print(arr.dtype) # data type of element of matrix array

(3, 4)
12
2
int64


In [50]:
print(arr[0][1]) # accessing the element of matrix array by indexing

20


In [57]:
# (inspection of array) numpy functions
a = [[30,40],[60,70]]
arr1 = np.array(a)
print(arr1)
print(arr1.shape) # dimension of array (rows, columns)
print(len(arr)) # no. of elem in an array
print(type(arr)) # data type of variable
print(arr.dtype) # data type of array
print(arr.astype(float)) # conversion of datatype

[[30 40]
 [60 70]]
(2, 2)
3
<class 'numpy.ndarray'>
int64
[[10. 20. 30. 40.]
 [50. 60. 70. 80.]
 [ 5. 15. 25. 35.]]


In [59]:
# Mathematical operations
a = np.array([30,40,50, 20, 10])
b = np.array([2, 4, 5, 6, 9])
print(a+b)
print(np.add(a,b))

[32 44 55 26 19]
[32 44 55 26 19]


In [64]:
a = np.array([[30,40,50], [20, 10, 7]])
b = np.array([[2, 4, 5], [6, 9, 8]])
print(a-b)
print(a-2)
print(np.divide(a,b))

[[28 36 45]
 [14  1 -1]]
[[28 38 48]
 [18  8  5]]
[[15.         10.         10.        ]
 [ 3.33333333  1.11111111  0.875     ]]


In [66]:
a = np.array([3,4,2,1])
b = np.array([2])
print(np.power(a, b))

[ 9 16  4  1]


In [69]:
a = np.array([9, 16, 4, 1])
print(np.sqrt(a)) # gives float array
print(np.sqrt(a).astype(int)) # convert to int array

[3. 4. 2. 1.]
[3 4 2 1]


In [4]:
a = [2,4,89,98]
b = [3,5,2,0]
print(a+b) # list concatanition happen

[2, 4, 89, 98, 3, 5, 2, 0]


In [8]:
# concatenate array by np
print(np.concatenate([a,b]))

[ 2  4 89 98  3  5  2  0]


In [17]:
a = np.array([[30,40,50], [20, 10, 7]])
b = np.array([[2, 4, 5], [6, 9, 8]])
print(np.concatenate([a,b], axis=0)) # concatenation
print(np.concatenate([a,b], axis=1)) # concatenation
print(np.hstack([a,b])) # horizontal concatenation
print(np.vstack([a,b])) # vertical concatenation

[[30 40 50]
 [20 10  7]
 [ 2  4  5]
 [ 6  9  8]]
[[30 40 50  2  4  5]
 [20 10  7  6  9  8]]
[[30 40 50  2  4  5]
 [20 10  7  6  9  8]]
[[30 40 50]
 [20 10  7]
 [ 2  4  5]
 [ 6  9  8]]


In [21]:
# split array
arr = np.array([2,3,4,5,6])
brr = np.array_split(arr,3)
print(brr) # array of array (splitted array)
print(brr[1])
print(brr[1][0])

[array([2, 3]), array([4, 5]), array([6])]
[4 5]
4


In [32]:
# functions append, insert, delete
print(np.append(a, [90,100])) # make 1d array from 2d array
print(np.append(arr, 9))

print(np.insert(arr, 1, 10000)) # array, index,  value
print(np.insert(a, [0,2], [1000], axis=0))

[ 30  40  50  20  10   7  90 100]
[2 3 4 5 6 9]
[    2 10000     3     4     5     6]
[[1000 1000 1000]
 [  30   40   50]
 [  20   10    7]
 [1000 1000 1000]]
